### ISSUE TITLE
2. Clone the ShinyPsych repository and make a pull request

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ClaudiaLearning#2]
Clone the ShinyPsych repository to your computer. Open the project in RStudio. Explore the repository to see how it is structured.

Make a minor change to the main project guide (in the vignettes), commit, and push it to the ShinyPsych GitHub page to make a pull request to the main repository.

I will then merge the pull request! Now you know how to make contributions to the repository

**Comment by claudiaputtinger** [comment]
after like 20 hours of thinking about what I could change I finally figured out that I don't know how to make a pull request from my local computer....

**Comment by ndphillips** [comment]
I'd recommend doing it with the GitHub desktop app (https://desktop.github.com/) this makes it really easy!

**Comment by claudiaputtinger** [comment]
I tried that with the IT but we couldn't make it work. Then they installed Sourcetree for me on my desktop but there I have the problem that I can not properly clone the repositories and as a consequence can not access them...
